# Generated by Django 4.2.3 on 2023-08-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('body', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
